package corba.robot;


/**
* corba/robot/RobotSeguidorInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from robot.idl
* martes 14 de diciembre de 2021 09H19' CET
*/

public interface RobotSeguidorInt extends RobotSeguidorIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RobotSeguidorInt
