package corba.robot;


/**
* corba/robot/RobotSeguidorIntPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from robot.idl
* martes 14 de diciembre de 2021 09H19' CET
*/

public class RobotSeguidorIntPOATie extends RobotSeguidorIntPOA
{

  // Constructors

  public RobotSeguidorIntPOATie ( corba.robot.RobotSeguidorIntOperations delegate ) {
      this._impl = delegate;
  }
  public RobotSeguidorIntPOATie ( corba.robot.RobotSeguidorIntOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public corba.robot.RobotSeguidorIntOperations _delegate() {
      return this._impl;
  }
  public void _delegate (corba.robot.RobotSeguidorIntOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void ObtenerEstado (corba.instantanea.EstadoRobotDHolder est)
  {
    _impl.ObtenerEstado(est);
  } // ObtenerEstado

  private corba.robot.RobotSeguidorIntOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class RobotSeguidorIntPOATie
