package corba;


/**
* corba/Echo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Echo.idl
* martes 19 de octubre de 2021 12H04' CEST
*/

public interface Echo extends EchoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Echo
