package corba;


/**
* corba/EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Echo.idl
* martes 19 de octubre de 2021 12H04' CEST
*/

public interface EchoOperations 
{

  // Methods
  String echoService (String input);
} // interface EchoOperations
