package corba.robot;


/**
* corba/robot/RobotSeguidorInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from robot.idl
* domingo 16 de enero de 2022 19H41' CET
*/

public interface RobotSeguidorInt extends RobotSeguidorIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RobotSeguidorInt
