package corba.camara;


/**
* corba/camara/CamaraIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from robot.idl
* martes 14 de diciembre de 2021 09H19' CET
*/

public interface CamaraIntOperations 
{
  corba.camara.suscripcionD SuscribirRobot (String IORrob);
} // interface CamaraIntOperations
