package corba.camara;


/**
* corba/camara/suscripcionD.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from robot.idl
* martes 14 de diciembre de 2021 09H19' CET
*/

public final class suscripcionD implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public corba.camara.IPYPortD iport = null;

  public suscripcionD ()
  {
  } // ctor

  public suscripcionD (int _id, corba.camara.IPYPortD _iport)
  {
    id = _id;
    iport = _iport;
  } // ctor

} // class suscripcionD
