package corba.consola;


/**
* corba/consola/ConsolaIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from robot.idl
* domingo 16 de enero de 2022 19H41' CET
*/

public interface ConsolaIntOperations 
{
  void ModificarEscenario (corba.khepera.escenario.EscenarioD esc);
  boolean estoyviva ();
} // interface ConsolaIntOperations
