package corba.khepera.escenario;

/**
* corba/khepera/escenario/EscenarioDHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from robot.idl
* domingo 16 de enero de 2022 19H41' CET
*/

public final class EscenarioDHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.khepera.escenario.EscenarioD value = null;

  public EscenarioDHolder ()
  {
  }

  public EscenarioDHolder (corba.khepera.escenario.EscenarioD initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.khepera.escenario.EscenarioDHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.khepera.escenario.EscenarioDHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.khepera.escenario.EscenarioDHelper.type ();
  }

}
