package corba.instantanea;


/**
* corba/instantanea/EstadoRobotD.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from robot.idl
* domingo 16 de enero de 2022 19H41' CET
*/

public final class EstadoRobotD implements org.omg.CORBA.portable.IDLEntity
{
  public String nombre = null;
  public int id = (int)0;

  //Referencia en formato String IOR
  public String IORrob = null;

  //Referencia en formato binario
  public corba.robot.RobotSeguidorInt refrob = null;
  public corba.instantanea.PuntosRobotD puntrob = null;
  public corba.khepera.robot.PosicionD posObj = null;
  public int idLider = (int)0;

  public EstadoRobotD ()
  {
  } // ctor

  public EstadoRobotD (String _nombre, int _id, String _IORrob, corba.robot.RobotSeguidorInt _refrob, corba.instantanea.PuntosRobotD _puntrob, corba.khepera.robot.PosicionD _posObj, int _idLider)
  {
    nombre = _nombre;
    id = _id;
    IORrob = _IORrob;
    refrob = _refrob;
    puntrob = _puntrob;
    posObj = _posObj;
    idLider = _idLider;
  } // ctor

} // class EstadoRobotD
